import os
import psycopg2
import validators
from dotenv import load_dotenv
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    get_flashed_messages
)
from datetime import date
from urllib.parse import urlparse
from page_analyzer.url_repository import UrlRepository

# Загружаем переменные окружения из .env файла
load_dotenv()

app = Flask(__name__)
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['DATABASE_URL'] = os.getenv('DATABASE_URL')


conn = psycopg2.connect(app.config['DATABASE_URL'])
repo = UrlRepository(conn)


def normalize_url(url):
    parsed = urlparse(url)
    return f"{parsed.scheme}://{parsed.netloc}"


create_base_query = """
DROP TABLE IF EXISTS urls CASCADE;
DROP TABLE IF EXISTS url_checks;

CREATE TABLE urls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    created_at DATE NOT NULL
);

CREATE TABLE url_checks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id INT REFERENCES urls(id) NOT NULL,
    status_code VARCHAR,
    h1 VARCHAR,
    title VARCHAR,
    description VARCHAR,
    created_at DATE NOT NULL
);
"""

with conn.cursor() as curs:
    curs.execute(create_base_query)
    conn.commit()


@app.route('/')
def index():
    messages = get_flashed_messages(with_categories=True)
    return render_template(
        'index.html',
        messages=messages
    )


@app.get('/urls')
def urls_get():
    urls = repo.get_content()
    return render_template(
        'urls/urls_list.html',
        urls=urls
    )


@app.post('/urls')
def urls_post():

    raw_url = request.form.get('url')

    if not validators.url(raw_url):
        flash('Некорректный URL', 'danger')
        messages = get_flashed_messages(with_categories=True)
        return render_template(
            'index.html',
            url=raw_url,
            messages=messages
        )

    url = {
        'name': normalize_url(raw_url),
        'created_at': date.today()
    }

    existing_url = repo.check_by_name(url)
    if existing_url:
        id = existing_url['id']
        flash('Страница уже существует', 'info')
    else:
        id = repo.create(url)
        flash('Страница успешно добавлена', 'success')

    return redirect(url_for('urls_show', id=id), code=302)


@app.route('/urls/<id>')
def urls_show(id):
    messages = get_flashed_messages(with_categories=True)
    url = repo.find(id)
    url_checks = repo.get_url_checks(id)

    return render_template(
        'urls/show.html',
        url=url,
        url_checks=url_checks,
        messages=messages
    )


@app.post('/urls/<id>/checks')
def url_checks(id):
    url_check = {
        'url_id': id,
        'status_code': '',
        'h1': '',
        'title': '',
        'description': '',
        'created_at': date.today()
    }

    repo.create_url_check(url_check)
    flash('Страница успешно проверена', 'success')

    return redirect(url_for('urls_show', id=id), code=302)
